# Site settings
title: Tatsuya Oiwa
email:
author: Tatsuya Oiwa
description: "Tatsuya Oiwa's blog"
baseurl:
url: "http://tatsuyaoiw.com"

# Google analytics
google_analytics: UA-11963754-5

# Optional features
animated: false
show_related_posts: false
show_post_footers: false

# Social icons
show_social_icons: true
github_username: tatsuyaoiw
twitter_username: tatsuyaoiw
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown: redcarpet
permalink: pretty
paginate: 10
sass:
  compressed: true
